# @package _global_

tag: 'nose/pointy'

prompts:
- prompt_target: 'nose'
  prompt_positive: 'pointy nose'
  prompt_negative: 'snub nose'
  pattern_target: 'nose'
- prompt_target: 'nose'
  prompt_positive: 'pointy nose'
  prompt_negative: 'snub nose'
  pattern_target: 'nose'
- prompt_target: 'nose'
  prompt_positive: 'sharp nose'
  prompt_negative: 'snub nose'
  pattern_target: 'nose'
- prompt_target: 'nose'
  prompt_positive: 'very pointy nose'
  prompt_negative: 'very snub nose'
  pattern_target: 'nose'

prefixes: ${combinations:'{,a photo of,a portrait of,a painting of} a {,beautiful} {,asian,african-american,caucasian,white,arab,black,african,american,south-american,indian} {man, woman, person, boy, girl, lady, adult, guy} {have, has} a'}
