run_type: ???
tag: ???

device: cuda

hydra:
  run:
    dir: outputs/${run_type}/${tag}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/${run_type}/${tag}/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
